In [1]:
3 + 5*4
#python is a calculator
#can use variables to store information

23

In [2]:
weight_kg = 60
#making a variable
#must run this to store this in memory
#must make variable to store long term
#equal sign called the "assignment"

In [5]:
print (weight_kg)
print (weight_kg*weight_kg)
#variable names can include letters, digits, underscores
#CANNOT START VARIABLE NAME WITH NUMBER
#variables are CASE-SENSITIVE (weight0 and Weight0 store different values)

60
3600


In [14]:
my_number = 3
my_float = 2.43434434
my_string = 'This is my string'
#different data types
#single or double quotes the same in Python

In [15]:
print(my_string, my_float)

This is my string 2.43434434


In [19]:
weight_kg_text = 'weight in kilograms:'
print(weight_kg_text, weight_kg)
print('weight in pounds:', weight_kg * 2.2)
print(weight_kg)
weight_kg = 100
print(weight_kg)
#store weight_kg to 100 changes it throughout file
#incrementing changes value to incrementing changes every time you run code

weight in kilograms: 100
weight in pounds: 220.00000000000003
100
100


In [20]:
x = 5
y = 6
print (x + y)

11


In [21]:
x = y
print (x + y)
#x now takes on value of y

12


In [22]:
mass = 47.5
age = 122
mass = mass * 2.0
age = age - 20
print(mass,age)

95.0 102


In [24]:
first, second = 'Grace', 'Shawn'
#first holds Grace, second holds Shawn
third,fourth = second, first
print(third,fourth)
#third holds Shawn now, fourth holds Grace

Shawn Grace


In [25]:
#numerical python (numpy) is a usfeful module in Python
#functions are stored in this library
import numpy

In [30]:
#with dot lets you use fxn in numpy
#tab should let you see fxn options
numpy.loadtxt(fname='inflammation-01.csv', delimiter = ",")

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.]])

In [29]:
medical_data = numpy.loadtxt(fname='inflammation-01.csv', delimiter = ",")
#store it so can use it
#2 paramaters for loadtxt: fname and delimiter

print(medical_data)

import numpy as np

In [33]:
medical_data = np.loadtxt(fname='inflammation-01.csv', delimiter = ",")
#first one still works because imported numpy b4 as numpy

In [34]:
print(type(medical_data))

<class 'numpy.ndarray'>


In [35]:
#array is important data type b/c it is how you store lots of info
#example:
a = [1,2,3,4]

In [36]:
print(a)

[1, 2, 3, 4]


In [39]:
print(a[4])
#Python counts starting with 0
#first element of array is 0th, second is 1st, etc.
#made this way because indexing a list originally define as DISTANCE FROM START; max 1 less than array length
#made to be like computer memory
#modern languages (R, MATLAB...) start at 1
#error = out of bounds/out of range

IndexError: list index out of range

In [40]:
print(a[3])

4


In [41]:
print(medical_data.dtype)
#64 is number of bytes

float64


In [42]:
#data types
##ints = 3, 6, 100
###floating point numbers: 3.434444, 1.2...

In [43]:
#always row,column for arrays
#number of rows and number of columns

print(medical_data.shape)

(54, 40)


In [48]:
print(medical_data.shape[1])

40


In [51]:
print(medical_data[0:4, 0:10])
#row = patients, columns = days
#rows 0 up to but not including 4, columns 0 up to but not including 10 (starting at 0)
#slicing terminology is such that go UP TO but not at fourth (fifth) position-->open vs closed set ("[ vs (")

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]]


In [52]:
print(medical_data[4])

[ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
  8.  6. 18.  4. 12.  5. 12.  7. 11.  5. 11.  3.  3.  5.  4.  4.  5.  5.
  1.  1.  0.  1.]


In [54]:
bruin = medical_data[:3, 36:]
print(bruin)

#default start is 0
#print rows 0, 1, and 2 (3 not included)
#print column 36 to the rest of the columns (39 is the last one)

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [56]:
print ('bruin in: \n',bruin)


bruin in: 
 [[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [57]:
print(np.mean(medical_data))

5.658333333333333


In [58]:
import time
print(time.ctime())
#fxn needs parentheses
#fxn with no variables above

Mon Jan 27 09:42:40 2020


In [59]:
maxval, minval = np.max(medical_data), np.min(medical_data)

In [60]:
stdval = np.std(medical_data)

In [64]:
print(max:',maxval', min:',minval,',stdev:',stdval')

SyntaxError: invalid syntax (<ipython-input-64-455397fd0eaa>, line 1)

In [65]:
patient_2 = medical_data[1,:]
patient_2_min = np.min(patient_2)
print(patient_2_min)

0.0


In [76]:
patient_means_down = np.mean(medical_data, axis=0)
print(len(patient_means_down))
#40 rows but no columns; done by stacking functions
#len gives length (ex. length of array)

#axis = 0 gives whatever function for each day (column-down)
#axis = 1 -->whatever function for each patient (row across)

40


In [77]:
#writing a function
#thing in parentheses is paramater you will put in
#tabs are very important (mostly use curly braces in other languages)
def my_func(name):
    print('Hello',name)
    

In [78]:
my_func("Omer")

Hello Omer


In [79]:
my_func(Omer)

NameError: name 'Omer' is not defined

In [80]:
#scope: x is contained within scope of this function (local variable, not global/function wide variable)
def square_minus(x):
    square = x*x
    square = square - 2
    return(square)
#return allows you to use stuff in certain calculations
#can put functions into functions

In [81]:
zzz = square_minus(10)
print(zzz)

98
