In [1]:
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])

first three characters: oxy
last three characters: gen


In [36]:
print(element[:4])
print(element[4:])
print(element[:])


oxyg
en
oxygen


In [3]:
element[-1]

'n'

In [4]:
element[-2]

'e'

In [5]:
element[1:-1]
#Counting using negative numbers on a string caused Python to count from the end of the word
#The colon tells Python to start counting at the place corresponding to the first character in the word up to but not including the place corresponding to the number after the colon
#Thus, with the above command, Python starts by giving the "1th" (i.e. the letter corresponding to "1," which isn't the first letter) letter in the word followed by the letter right before the "-1th" letter in the word, which is "e"

'xyge'

In [6]:
element[3:3]
#Python is going from letter 3 to up to but not including letter 3, so the 2 sides of the colon essentially negate each other, and the later information is taken into considertation by Python, leading to an empty string


''

In [7]:
import numpy
medical_data = numpy.loadtxt(fname='inflammation-01.csv', delimiter = ",")

In [8]:
medical_data[3:3,4:4]
#For similar reasons as to what I described above (essentially two contradicting commands), data[3:3,4:4] would print an empty array

array([], shape=(0, 0), dtype=float64)

In [9]:
medical_data[3:3,:]
#This command tells Python to make an array with no rows and all the columns in medical_data
#Thus, the data in the rows in removed, leaving an array with 40 empty columns

array([], shape=(0, 40), dtype=float64)

In [10]:
A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
D=A[0:3,0]
print('D: ')
print(D)

E=A[0:3,2]
print('E: ')
print(E)

solution=numpy.vstack([D,E])
print('Solution: ')
print(solution)

D: 
[1 4 7]
E: 
[3 6 9]
Solution: 
[[1 4 7]
 [3 6 9]]


In [16]:
# 1.) Each row of inflammation data represents data taken at different times from ONE INDIVIDUAL. Therefore, numpy.diff would best be used across a row in order to track changes in inflammation over time.
# 2.) A (60,40) array plugged into numpy.diff would produce a (60,39) array because numpy.diff acts on the last ("-1st") axis in the array by default (the columns in this case) and the function results in an row or column that is one value smaller than the one that was originally there.
print('Testing Solution to #2: ')
print('Inflammation Data O.G. Shape: ')
print(medical_data.shape)
Diffed=(numpy.diff(medical_data))
print('New Shape: ')
print(Diffed.shape)


Testing Solution to #2: 
Inflammation Data O.G. Shape: 
(54, 40)
New Shape: 
(54, 39)


In [38]:
AbsDiff=abs(Diffed)
MaxDiff=numpy.nanmax(AbsDiff, axis=1)
print('Maximum Difference for Each Patient: ')
print(MaxDiff)

# 3.) Convert the array containing the differences in inflammation for each patient to absolute values. Then find the maximum value for each row. Since, with this method, the differences are converted to their absolute values, the maximum difference in inflammation for each patient will be shown regardless of whether the change was an increase or decrease.



Maximum Difference for Each Patient: 
[12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11.
 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11.
 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11.]


In [37]:
print(MaxDiff.shape)
#checking my work to make sure each patient is accounted for

(54,)
